### ISSUE TITLE
Subscription quota has been reached despite no imports.

### ISSUE THREAD

**Issue by ghost** [luispadron/YouTube-Subscription-Importer#1]
After setting up everything and running the script I immediately get the following:
`Subscription quota has been reached.
All subscribed channels were saved to channels_subscribed.txt.
Try again at a later time...`

However no file channels_subscribed.txt get created and zero subscriptions are imported from the xml file to the youtube channel. 

Any idea what could be wrong? Tried multiple times during the day without any progress.

**Comment by luispadron** [comment]
Hm i'm honestly not sure. This was a quick and simple script i made forever ago, so I haven't really maintained it (sorry)!

However, from the error it looks like the API key you're using is either at the limit OR the script is just not working anymore. I'm super busy with work/projects right now and don't have the time to invest much into this repo. Sorry I can't be much more help.
